### ISSUE TITLE
typo hwolerjs in haxelib.json

### ISSUE THREAD

**Issue by inc0der** [LunaTechsDev/PaperTea#1]
https://github.com/LunaTechsDev/PaperTea/blob/39dc88b6d82141b4dde849efba0e1eca9cde44ae/haxelib.json#L17

I think this effects installation of PaprTea using `lix install gh:LunaTechsDev/PaperTea#dev` in a new project. I get the error 

![image](https://user-images.githubusercontent.com/14813394/129790945-bfac6b1f-7c6e-4ab2-8d85-67b11df9eae4.png)

@KinoAR Does this happen to you? Or is it just because I'm having issues with my global install of `Haxe`

**Comment by KinoAR** [comment]
Yea we'll update this it's for the Haxelib when we publish the library

**Comment by inc0der** [comment]
Ok, I'll do this for you right now, I'll send a PR when ready.
